// Nice program made by my collegue Francesco Tomba, check https://github.com/lykos98

#include <stdlib.h>
#include <unistd.h>
#include <stdio.h>
#include <math.h>
#include <string.h>
#include <stdbool.h>

#define XWIDTH 256
#define YWIDTH 256
#define MAXVAL 65535

#if ((0x100 & 0xf) == 0x0)
#define I_M_LITTLE_ENDIAN 1
#define swap(mem) (((mem) & (short int)0xff00) >> 8) + \
                      (((mem) & (short int)0x00ff) << 8)
#else
#define I_M_LITTLE_ENDIAN 0
#define swap(mem) (mem)
#endif

void write_pgm_image(void *image, int maxval, int xsize, int ysize, const char *image_name)
/*
 * image        : a pointer to the memory region that contains the image
 * maxval       : either 255 or 65536
 * xsize, ysize : x and y dimensions of the image
 * image_name   : the name of the file to be written
 *
 */
{
    FILE *image_file;
    image_file = fopen(image_name, "w");

    // Writing header
    // The header's format is as follows, all in ASCII.
    // "whitespace" is either a blank or a TAB or a CF or a LF
    // - The Magic Number (see below the magic numbers)
    // - the image's width
    // - the height
    // - a white space
    // - the image's height
    // - a whitespace
    // - the maximum color value, which must be between 0 and 65535
    //
    // if he maximum color value is in the range [0-255], then
    // a pixel will be expressed by a single byte; if the maximum is
    // larger than 255, then 2 bytes will be needed for each pixel
    //

    int color_depth = 1 + (maxval > 255);

    fprintf(image_file, "P5\n# generated by\n# put here your name\n%d %d\n%d\n", xsize, ysize, maxval);

    // Writing file
    fwrite(image, 1, xsize * ysize * color_depth, image_file);

    fclose(image_file);
    return;

    /* ---------------------------------------------------------------
       TYPE    MAGIC NUM     EXTENSION   COLOR RANGE
             ASCII  BINARY
       PBM   P1     P4       .pbm        [0-1]
       PGM   P2     P5       .pgm        [0-255]
       PPM   P3     P6       .ppm        [0-2^16[

    ------------------------------------------------------------------ */
}

void read_pgm_image(void **image, int *maxval, int *xsize, int *ysize, const char *image_name)
/*
 * image        : a pointer to the pointer that will contain the image
 * maxval       : a pointer to the int that will store the maximum intensity in the image
 * xsize, ysize : pointers to the x and y sizes
 * image_name   : the name of the file to be read
 *
 */
{
    FILE *image_file;
    image_file = fopen(image_name, "r");

    *image = NULL;
    *xsize = *ysize = *maxval = 0;

    char MagicN[3];
    char *line = NULL;
    size_t k, n = 0;

    // get the Magic Number
    k = fscanf(image_file, "%2s%*c", MagicN);

    // skip all the comments
    k = getline(&line, &n, image_file);
    while ((k > 0) && (line[0] == '#'))
        k = getline(&line, &n, image_file);

    if (k > 0)
    {
        k = sscanf(line, "%d%*c%d%*c%d%*c", xsize, ysize, maxval);
        if (k < 3)
            fscanf(image_file, "%d%*c", maxval);
    }
    else
    {
        *maxval = -1; // this is the signal that there was an I/O error
                      // while reading the image header
        free(line);
        return;
    }
    free(line);

    int color_depth = 1 + (*maxval > 255);
    unsigned int size = *xsize * *ysize * color_depth;

    if ((*image = (char *)malloc(size)) == NULL)
    {
        fclose(image_file);
        *maxval = -2; // this is the signal that memory was insufficient
        *xsize = 0;
        *ysize = 0;
        return;
    }

    if (fread(*image, 1, size, image_file) != size)
    {
        free(image);
        image = NULL;
        *maxval = -3; // this is the signal that there was an i/o error
        *xsize = 0;
        *ysize = 0;
    }

    fclose(image_file);
    return;
}

void swap_image(void *image, int xsize, int ysize, int maxval)
/*
 * This routine swaps the endianism of the memory area pointed
 * to by ptr, by blocks of 2 bytes
 *
 */
{
    if (maxval > 255)
    {
        // pgm files has the short int written in
        // big endian;
        // here we swap the content of the image from
        // one to another
        //
        unsigned int size = xsize * ysize;
        for (int i = 0; i < size; i += 2)
            ((unsigned short int *)image)[i] = swap(((unsigned short int *)image)[i]);
    }
    return;
}

int main(int argc, char **argv)
{
    char *f1 = argv[1];
    char *f2 = argv[2];
    printf("this machine is %s\n", (I_M_LITTLE_ENDIAN) ? "little endian" : "big endian");
    void *image1;
    int nrows, ncols, max;
    read_pgm_image(&image1, &max, &ncols, &nrows, f1);
    if (I_M_LITTLE_ENDIAN)
        swap_image(image1, ncols, nrows, max);

    void *image2;
    read_pgm_image(&image2, &max, &ncols, &nrows, f2);
    if (I_M_LITTLE_ENDIAN)
        swap_image(image2, ncols, nrows, max);
    printf("%d %d %d\n", max, nrows, ncols);
    FILE *out;
    out = fopen("err.log", "w");
    int error = 0;
    if (max > 255)
    {
        for (int i = 0; i < ncols * nrows; i++)
        {
            if (((unsigned short *)image1)[i] != ((unsigned short *)image2)[i])
            {
                fprintf(out, "error at %d %d diff %d %d %d \n", i / ncols, i % ncols, ((unsigned short *)image1)[i] - ((unsigned short *)image2)[i], ((unsigned short *)image1)[i], ((unsigned short *)image2)[i]);
                error += 1;
            }
            // if(i % 1000 == 0) printf("%d\n", ((unsigned short*)image1)[i] - ((unsigned short*)image1)[i] );
        }
    }
    else
    {
        for (int i = 0; i < ncols * nrows; i++)
        {
            if (((unsigned char *)image1)[i] != ((unsigned char *)image2)[i])
            {
                fprintf(out, "error at %d %d diff %d %d %d\n", i / ncols, i % ncols, ((unsigned char *)image1)[i] - ((unsigned char *)image2)[i], ((unsigned char *)image1)[i], ((unsigned char *)image2)[i]);
                error += 1;
            }
            // if(i % 1000 == 0) printf("%d\n", ((unsigned short*)image1)[i] - ((unsigned short*)image1)[i] );
        }
    }
    printf("-----\nTot errors occurred: %d out of %d pixels %.2f pc \nMore info in err.log\n", error, nrows * ncols, ((float)error) / (nrows * ncols) * 100);
    fclose(out);

    return 0;
}
